### ISSUE TITLE
Impossible to compile after clone

### ISSUE THREAD

**Issue by beltransen** [HesaiTechnology/HesaiLidar_PandarGeneral_ROS#11]
## Tested environments:
- OS: Ubuntu 18.04 & 20.04
- ROS version: ROS Melodic & Noetic
## Error
Apart from the compiling errors reported in https://github.com/HesaiTechnology/HesaiLidar_PandarGeneral_ROS/issues/8, there are some errors introduced in the latest commits. As can be seen in the image below, the code is trying to used an undeclared variable. This error exists in many functions, where the parameter is called **pkt** instead of **packet**. 

![image](https://user-images.githubusercontent.com/2643936/87144063-78c93280-c2a7-11ea-9173-e18aa063b955.png)

Apparently, it is just a variable naming issue. However, after replacing **packet** by **pkt** in the affected methods, a new error is thrown:

![image](https://user-images.githubusercontent.com/2643936/87143413-52ef5e00-c2a6-11ea-8eb3-3b5835bc453c.png)

It would be desirable to have a reliable driver with periodical updates that offer support to OS and dependencies version upgrades. However, at least it should be mandatory that known issues are solved and **commits are tested before being pushed to the repository**.

**Comment by yangfanFred** [comment]
Hi beltransen,

Our prjects were mostly built and tested on Ubuntu16.04 & ROS Kinetic since this evnironment are the most common used and stable combo. We didn't offically support Ubuntu 20.04 yet, we will look into this requirement and give feedbacks very soon.

Thank you

**Comment by beltransen** [comment]
It looks like your recent commits solved the problem. I'm closing the issue.

**Comment by yangfanFred** [comment]
Thanks beltransen
