### ISSUE TITLE
Problem with publishing topic /raw points 

### ISSUE THREAD

**Issue by remitoudic** [HesaiTechnology/HesaiLidar_PandarGeneral_ros#6]
Hello , 

I got the chance to test a lidar  Pandar 64 .  I followed instructions from Github to install the ROS packages  all was successful . Unfortunately I am not able to receive any  thing from topic /rawpoints. 
I use Ubuntu 18.04 and ROS melodic . 

I guess I have a setting problem . 

Can you help me maybe ?  It would be nice :) 
++++++++++++++++++++++++++++++
I  got from system following : 
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://aicore:45053/

SUMMARY

PARAMETERS
 * /hesai_lidar/gps_port: 10110
 * /hesai_lidar/laser_count: 64
 * /hesai_lidar/laser_return_type: 1
 * /hesai_lidar/lidar_correction_file: /home/aicore/rosw...
 * /hesai_lidar/lidar_recv_port: 2368
 * /hesai_lidar/lidar_type: 
 * /hesai_lidar/pcap_file: 
 * /hesai_lidar/pcldata_type: 0
 * /hesai_lidar/server_ip: 10.2.25.25
 * /hesai_lidar/server_port: 9870
 * /hesai_lidar/start_angle: 0.0
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    hesai_lidar (hesai_lidar/hesai_lidar_node)

ROS_MASTER_URI=http://localhost:11311

process[hesai_lidar-1]: started with pid [24796]
TCP Command Client Init Success!!!

**Comment by yangfanFred** [comment]
hihi ：）

First of all, try using our PandarView software to connect Lidar so to make sure there's no problem with the Lidar itself. Please see our user mannual about how to connect Lidar and use PandarView.

Also please provide the Lidar settings web page information and Sever ip setting you are using.

**Comment by remitoudic** [comment]
Thank you  Yangfang . 
Unfortunately  I don't have the Lidar anymore but could test it with windows software and it was working     :+1: 
Just a remark for the people of Hesai , the windows software given on the usb stick with the lidar was outdated  and did not work for the Pandar 64 .  So it someone has the same issue download the new version  directly from the  Hesai website

**Comment by yangfanFred** [comment]
Thanks a lot remitoudic
