### ISSUE TITLE
No install folder after catkin_make -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by danijel-fmci** [HesaiTechnology/HesaiLidar_PandarGeneral_ros#67]
Hi,

I followed the steps from README.md, but after the build with `catkin_make -DCMAKE_BUILD_TYPE=Release` there is no install folder. Please take a look at the attached command history.
[HesaiLidar_General_ROS_terminal_commands_history.txt](https://github.com/HesaiTechnology/HesaiLidar_General_ROS/files/10785857/HesaiLidar_General_ROS_terminal_commands_history.txt)

However, I found another tutorial on YT on [Hesai Lidar Tutorial #3: Run ROS Driver with Connected Lidar](https://www.youtube.com/watch?v=Yx7oZm6ya3U) and after executing `catkin build --force-cmake`  I got install folder.
But still do not get the timestamp and point size in terminal output as per YT tutorial. 
Please see attached command history:
[[Youtube ]- Hesai Lidar Tutorial #3 Run ROS Driver with Connected Lidar_terminal_commands_history.txt](https://github.com/HesaiTechnology/HesaiLidar_General_ROS/files/10786135/Youtube.-.Hesai.Lidar.Tutorial.3.Run.ROS.Driver.with.Connected.Lidar_terminal_commands_history.txt)
![hesai_lidar launch](https://user-images.githubusercontent.com/111062102/220158676-f622a2a2-06b9-4c73-8a7a-299a8f076696.PNG)

The lidar is working properly using Pandar.exe.
![Pandar_capture](https://user-images.githubusercontent.com/111062102/220159229-2fdb4d1c-27c9-4600-b3af-3ab8537a1851.PNG)

The host OS is Windows 10, installed WSL1 and Ubuntu 18.04 with ROS melodic.
[host_spec.txt](https://github.com/HesaiTechnology/HesaiLidar_General_ROS/files/10786194/host_spec.txt)

Thank you.

Best,
Danijel

**Comment by yangfanFred** [comment]
Hi Danijel,

uncomment print flag in main.c to enable output point info
![image](https://user-images.githubusercontent.com/59682908/220809609-213cea6a-e894-4a9a-a8d1-5ac2e06afc0f.png)

**Comment by danijel-fmci** [comment]
Hi @yangfanFred 

Now it outputs the timestamp and corresponding point size in the terminal.
Thank you very much.

Best,
Danijel

![roslaunch_hesai_lidar_OK_Timestamp_Point_Size_27-02-2023](https://user-images.githubusercontent.com/111062102/221616867-3858ee8e-e0af-45d1-9f3f-4624e94777ec.PNG)
